version: '2'

services:
  backend-app:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/aviasales
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - backend
      - frontend

  frontend-app:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "80:80" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - backend-app
    networks:
      - frontend
  db:
    container_name: db
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=aviasales
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
  frontend: