spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aviasales
    password: 5361988
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-stacktrace: never


